from aiogram.fsm.state import State, StatesGroup

class Registration(StatesGroup):
    agreement = State()
    gender = State()
    age = State()
    social_status = State()
    kids = State()
    education = State()
    job = State()
    prayer = State()
    smoking = State()
    hijab = State()
    height = State()
    weight = State()
    skin_color = State()
    health = State()
    country = State()
    state_name = State()
    travel_willingness = State()
    marriage_type = State()
    housing = State()
    partner_specs = State()
    bio = State()
